version: "4"
services:
 mysql:
  image: mysql:8.3.0
  container_name: mysql
  environment:
   MYSQL_ROOT_PASSWORD: sanjay_p90
  ports:
  - "3306:3306"
  volumes:
  - ./mysql:/var/lib/mysql
  - .docker/mmysql/init.sql:/docker-entrypoint-initdb.d/init.sql