version: "4"
services:
 mysql:
  image: mysql:8.3.0
  container_name: order-service-mysql
  environment:
   MYSQL_ROOT_PASSWORD: sanjay_p90
  ports:
  - :3306
  volumes:
  - ./mysql:/var/lib/mysql
  - .docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  