
version: '4'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - ./data:/data/db

      
      #grafana       
#  loki:
 #   image: grafana/loki:main
  #  command: ['-config.file=/etc/loki/local-config.yaml']
   # ports:
    #  - '3100:3100'
      
#  prometheus:
#    image: prom/prometheus:v2.46.0
 #  command:
  #    - --enable-feature=exemplar-storage
   #   - --config.file=/etc/prometheus/prometheus.yml
    #volumes:
#      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
 #   ports:
  #    - '9090:9090'